# Default values for foobar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tor:
  image:
    repository: "ghcr.io/jbgosselin/tor-client"
    pullPolicy: Always
    tag: "0.4"

image:
  repository: "ghcr.io/jbgosselin/bitcoin-core"
  pullPolicy: Always
  tag: "25.1"

termination:
  gracePeriodSeconds: 600

securityContext:
  runAsUser: 568
  runAsGroup: 568

extraArgs: []

timezone: ''

enableResourceLimits: false
cpuLimit: 2000m
memLimit: 1Gi

bitcoinData:
  datasetName:
  mountPath: /var/lib/bitcoin
  hostPath:
